name: Rust

on:
  push:
    tags:
      - v*
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build software release
        run: cargo build --verbose
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nsfilho/echo-webserver
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'push tag' }}
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
